apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: item-catalog-service
  labels:
    run: item-catalog-service
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: item-catalog-service
    spec:
      containers:
        - name: item-catalog-service # confution
          image: item-catalog #509245120947.dkr.ecr.us-east-1.amazonaws.com/my-app:item-catalog This will be the url of the ecr image
          imagePullPolicy: Never #Always # This will pull the image from aws ecr always , is not set to Always will get the old images and changes will be not reflected
          ports:
            - containerPort: 8763
              protocol: TCP
